[project]
name = 'bonding-curve-dex'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.bonding-curve-dex]
path = 'contracts/bonding-curve-dex.clar'
clarity_version = 2
epoch = 2.5

[contracts.leo]
path = 'contracts/leo.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.5

[contracts.welsh]
path = 'contracts/welsh.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
